services: 
  api:
    build: .
    links:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3000:3000"
    networks:
      - redis
  redis: 
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - /var/redis/data:/data
    networks:
      - redis
networks:
  redis:
    driver: bridge